language: c
compiler:
  - gcc
  - clang
os:
  - linux
  - osx

before_install:
  - if [[ $TRAVIS_OS_NAME == linux ]]; then sudo apt-get update -qq && sudo apt-get install -y libssl-dev libsasl2-dev libcurl4-openssl-dev libjansson-dev ; fi
  - if [[ $TRAVIS_OS_NAME == osx ]]; then brew install openssl curl jansson ; fi

script:
  - ./bootstrap.sh
  - if [[ $TRAVIS_OS_NAME == osx ]]; then otool -L kafkacat ; else ldd kafkacat ; fi
  - ./kafkacat -U

